/**
 * @file drv8703.c
 * @brief Source file for DRV8703 driver functions
 * Handles SPI communication and driver configuration.
 */

#include "drv8703.h"
#include "stm32g4xx_hal_spi.h"
#include "stm32g4xx_hal_gpio.h"

SPI_HandleTypeDef DRV_SPI_INTERFACE;

/**
 * @brief Initializes the DRV8703 driver.
 * Configures the SPI interface and initializes required settings.
 * @return true if initialization is successful, false otherwise.
 */
void DRV_init(void) {
    MX_SPI_init();												//can fail; check return value?
    MX_GPIO_init();

	char pData[6] = {0};
	DRV_read(DRV_MAIN, (unsigned char *)pData);                 // dummy read
	DRV_modify_set(DRV_MAIN, DRV_MAIN_CLR_FLT_MASK);            // clear lock

    DRV_write(DRV_IDRIVE_WD, DRV_IDRIVE_WD_IDRIVE_MASK(0b101)); // sets correct IDRIVE current
    DRV_write(DRV_CONFIG, DRV_CONFIG_GAIN_CS_MASK(0b11));       // gain current
}

/**
 * @brief Writes data to a specific register in the DRV8703 driver.
 * @param address 4-bit register address.
 * @param data 8-bit data to be written.
 * @return true if write operation is successful, false otherwise.
 */
bool DRV_write(uint8_t address, uint8_t data) {
    uint8_t message[2] = {0}, buffer = 0;
    bool success = true;

    if (address > DRV_REG_MAP_SIZE) success = false;
    else {
    	message[0] = DRV_ADDR_MASK(address);
    	message[1] = data;
        HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_RESET);
        if (HAL_SPI_TransmitReceive(&DRV_SPI_INTERFACE, message, &buffer, 2, DRV_SPI_TIMEOUT) != HAL_OK) {
            success = false;
        }
        HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
    }

    return success;
}

/**
 * @brief Reads data from a specific register in the DRV8703 driver.
 * @param address 4-bit register address.
 * @param data Pointer to store the read 8-bit data.
 * @return true if read operation is successful, false otherwise.
 */
bool DRV_read(uint8_t address, uint8_t* data) {
		bool success = true;
		uint8_t message = 0, buffer = 0;

	    if (address > 0x0F) success = false;
	    else {
	    	message = DRV_READWRITE_MASK | DRV_ADDR_MASK(address);
	    	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_RESET);
	        if (HAL_SPI_TransmitReceive(&DRV_SPI_INTERFACE, &message, &buffer, 2, DRV_SPI_TIMEOUT) != HAL_OK) {
	            success = false;
	        }
	        HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
	    }
	    *data = (buffer & 0x00FF);

    return success;
}

/**
 * @brief Sets data in specific register in the DRV8703 driver.
 * @param address 4-bit register address.
 * @param data to be set, all unmentioned bits will remain unchanged.
 * @return true if write operation is successful, false otherwise.
 */
bool DRV_modify_set(uint8_t address, uint8_t data) {
	uint8_t reg = 0;
    bool success = 0;

	success = DRV_read(address, &reg);
    if (success) {
        reg |= data;
        success = DRV_write(address, reg);
    }
    return success;
}

/**
 * @brief Modifies data in specific register in the DRV8703 driver.
 * @param address 4-bit register address.
 * @param data to be reset, all unmentioned bits will remain unchanged.
 * @return true if write operation is successful, false otherwise.
 */
bool DRV_modify_reset(uint8_t address, uint8_t data) {
	uint8_t reg = 0;
    bool success = 0;

	success = DRV_read(address, &reg);
    if (success) {
        reg &= ~data;
        success = DRV_write(address, reg);
    }
    return success;
}

/**
 * @brief Writes data to multiple registers in the DRV8703 driver.
 * @param data Pointer to an array containing data for registers.
 * @param filter Bit mask to filter out specific registers.
 * @return true if write operation is successful, false otherwise.
 */
bool DRV_writeRegister(uint8_t* data, uint8_t filter) {
    bool success = true;

    for (int i = 0; i < DRV_REG_MAP_SIZE + 1; i++) {
        if (!(filter & (1<<(DRV_REG_MAP_SIZE-i)))) {
            success = DRV_write(DRV_REG_MAP_SIZE-i, data[i]);
            if (!success) break;
        }
    }

    return success;
}

/**
 * @brief Reads data from all registers in the DRV8703 driver.
 * @param data Pointer to an array where register data will be stored.
 * @param filter Bit mask to filter out specific registers.
 * @return true if read operation is successful, false otherwise.
 */
bool DRV_readRegister(uint8_t* data, uint8_t filter) {
    bool success = true;
    uint8_t* pData = data;

    for (int i = 0; i < DRV_REG_MAP_SIZE; i++) {
        if (!(filter & (1<<(DRV_REG_MAP_SIZE-i)))) {
            success = DRV_read(DRV_REG_MAP_SIZE-i, data);
            if (!success) break;
            data++;
        }
    }
    data = pData;

    return success;
}

/**
* @brief THIS IS AUTOGENERATED BY STM32MX, it overides the
* __weak verions defined in the stm HAL via linker and is
* used in HAL_SPI_Init used in DRV_init.
*/
int MX_SPI_init() {
	bool OK = 0;

	DRV_SPI_INTERFACE.Instance = SPI3;
    DRV_SPI_INTERFACE.Init.Mode = SPI_MODE_MASTER;
    DRV_SPI_INTERFACE.Init.Direction = SPI_DIRECTION_2LINES;
    DRV_SPI_INTERFACE.Init.DataSize = SPI_DATASIZE_8BIT;
    DRV_SPI_INTERFACE.Init.CLKPolarity = SPI_POLARITY_LOW;
    DRV_SPI_INTERFACE.Init.CLKPhase = SPI_PHASE_2EDGE;
    DRV_SPI_INTERFACE.Init.NSS = SPI_NSS_SOFT;
    DRV_SPI_INTERFACE.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_256;
    DRV_SPI_INTERFACE.Init.FirstBit = SPI_FIRSTBIT_MSB;
    DRV_SPI_INTERFACE.Init.TIMode = SPI_TIMODE_DISABLE;
    DRV_SPI_INTERFACE.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
    DRV_SPI_INTERFACE.Init.CRCPolynomial = 7;
    DRV_SPI_INTERFACE.Init.CRCLength = SPI_CRC_LENGTH_DATASIZE;
    DRV_SPI_INTERFACE.Init.NSSPMode = SPI_NSS_PULSE_DISABLE;
    if (HAL_SPI_Init(&DRV_SPI_INTERFACE) != HAL_OK) OK = 0;
    else OK = 1;

    return OK;

}

void HAL_SPI_MspInit(SPI_HandleTypeDef* spiHandle) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    if(spiHandle->Instance==SPI3) {
        __HAL_RCC_SPI3_CLK_ENABLE();

        __HAL_RCC_GPIOC_CLK_ENABLE();
        /**SPI3 GPIO Configuration
        PC10     ------> SPI3_SCK
        PC11     ------> SPI3_MISO
        PC12     ------> SPI3_MOSI
        */
        GPIO_InitStruct.Pin = GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12;
        GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
        GPIO_InitStruct.Pull = GPIO_PULLUP;
        GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
        GPIO_InitStruct.Alternate = GPIO_AF6_SPI3;
        HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
    }
}

void HAL_SPI_MspDeInit(SPI_HandleTypeDef* spiHandle) {
    if(spiHandle->Instance==SPI3) {
        __HAL_RCC_SPI3_CLK_DISABLE();
        /**SPI3 GPIO Configuration
        PC10     ------> SPI3_SCK
        PC11     ------> SPI3_MISO
        PC12     ------> SPI3_MOSI
        */
        HAL_GPIO_DeInit(GPIOC, GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12);
    }
}


void MX_GPIO_init() {
	GPIO_InitTypeDef GPIO_InitStruct = {0};

	/* GPIO Ports Clock Enable */
	__HAL_RCC_GPIOC_CLK_ENABLE();
	__HAL_RCC_GPIOF_CLK_ENABLE();
	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_GPIOB_CLK_ENABLE();

	/*Configure GPIO pin Output Level */
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1|GPIO_PIN_4, GPIO_PIN_SET);

	/*Configure GPIO pin : PA1 */
	GPIO_InitStruct.Pin = GPIO_PIN_1;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
	HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

	/*Configure GPIO pin : PA4 */
	GPIO_InitStruct.Pin = GPIO_PIN_4;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}
