/**
 * @file tmp112.c
 * @brief Source file for TMP112 temperature sensor driver functions
 * Handles I2C communication and driver configuration.
 */
#include "tmp112.h"

I2C_HandleTypeDef 	TMP_I2C_INTERFACE;

void TMP_init() {
	MX_I2C_Init();

    for (uint8_t i = TMP_ADDR_DEFAULT; i < TMP_ADDR_AMOUNT + TMP_ADDR_DEFAULT; i++) {
        TMP_setConfig(i, TMP_CONFIG_FAULT_QUEUE_MASK(1));
        TMP_setConfig(i, TMP_CONFIG_POLARITY_MASK);
        TMP_setTLow(i, 60);
        TMP_setTHigh(i, 80);
        TMP_getTemperatureSingle(i);
    }
}

float TMP_getTemperature(void) {
    uint16_t average = 0;

    for (uint8_t i = 0; i < TMP_ADDR_AMOUNT; i++) {
        average += TMP_getTemperatureSingle(i + TMP_ADDR_DEFAULT);
    }

    average /= TMP_ADDR_AMOUNT;
    return average;
}


float TMP_getTemperatureSingle(uint8_t address) {
	int16_t temperature = TMP_read(address, TMP_TEMPERATURE) >> 4;
    return TMP_data_to_celcius(temperature);
}

uint8_t TMP_setTLow(uint8_t address, float celcius) {
    return TMP_write(address, TMP_TLOW, TMP_data_to_celcius(celcius));
}

uint8_t TMP_setTHigh(uint8_t address, float celcius) {
    return TMP_write(address, TMP_THIGH, TMP_data_to_celcius(celcius));
}

uint8_t TMP_setConfig(uint8_t address, uint16_t data) {
    return TMP_write(address, TMP_CONFIG, data);
}

uint8_t TMP_write(uint8_t address, uint8_t reg, uint16_t data) {
    uint8_t OK = 1;
    uint8_t buf[2] = {(data >> 8 & 0xFF), (data & 0xFF)};

    if (HAL_I2C_Mem_Write(&TMP_I2C_INTERFACE, address, reg, 1, buf, 2, HAL_MAX_DELAY) != HAL_OK) OK = 0;
    return OK;
}


uint16_t TMP_read(uint8_t address, uint8_t reg) {
    uint8_t pData[2] = {0};
    uint16_t data = 0;

    if (HAL_I2C_Mem_Read(&TMP_I2C_INTERFACE, address, reg, 1, pData, 2, HAL_MAX_DELAY) != HAL_OK) return 0xFFFF;
    data = ((uint16_t)pData[0] << 8) | pData[1];
    return data;
}


uint16_t TMP_celcius_to_data(float celcius) {
    return (uint16_t)(celcius / TMP_DEGREE_RESOLUTION);
}

float TMP_data_to_celcius(uint16_t data) {
    return (float)(data * TMP_DEGREE_RESOLUTION);
}

void TMP_error(void) {
	while(1);
}

/**
* @brief THIS IS AUTOGENERATED BY STM32MX, it overides the
* __weak verions defined in the stm HAL via linker and is
* used in HAL_SPI_Init used in DRV_init.
*/
void MX_I2C_Init(void)
{
	TMP_I2C_INTERFACE.Instance = I2C3;
	TMP_I2C_INTERFACE.Init.Timing = 0x40B285C2;
	TMP_I2C_INTERFACE.Init.OwnAddress1 = 0;
	TMP_I2C_INTERFACE.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
	TMP_I2C_INTERFACE.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
	TMP_I2C_INTERFACE.Init.OwnAddress2 = 0;
	TMP_I2C_INTERFACE.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
	TMP_I2C_INTERFACE.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
	TMP_I2C_INTERFACE.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;\

	if (HAL_I2C_Init(&TMP_I2C_INTERFACE) != HAL_OK)
	{
		TMP_error();
	}
	if (HAL_I2CEx_ConfigAnalogFilter(&TMP_I2C_INTERFACE, I2C_ANALOGFILTER_ENABLE) != HAL_OK)
	{
		TMP_error();
	}
	if (HAL_I2CEx_ConfigDigitalFilter(&TMP_I2C_INTERFACE, 0) != HAL_OK)
	{
		TMP_error();
	}
}

void HAL_I2C_MspInit(I2C_HandleTypeDef* i2cHandle)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};
  if(i2cHandle->Instance==I2C3)
  {
    PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_I2C3;
    PeriphClkInit.I2c3ClockSelection = RCC_I2C3CLKSOURCE_PCLK1;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
    {
      TMP_error();
    }

    __HAL_RCC_GPIOC_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_8|GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_OD;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF8_I2C3;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
    __HAL_RCC_I2C3_CLK_ENABLE();
  }
}

void HAL_I2C_MspDeInit(I2C_HandleTypeDef* i2cHandle)
{

  if(i2cHandle->Instance==I2C3)
  {
    __HAL_RCC_I2C3_CLK_DISABLE();
    HAL_GPIO_DeInit(GPIOC, GPIO_PIN_8);
    HAL_GPIO_DeInit(GPIOC, GPIO_PIN_9);
  }
}
